### ISSUE TITLE
Hi, I created tiny port of vgg16 to tensorflow

### ISSUE THREAD

**Issue by hcl14** [rgeirhos/texture-vs-shape#10]
It's quite lame implementation. I see that restoring the picture from backpropagated features is approximately the same as with vanilla vgg16. Also, colors are also preserved while I thought that the model should ignore colors. 

 [https://github.com/hcl14/Stylized-Imagenet-Tensorflow-weights](https://github.com/hcl14/Stylized-Imagenet-Tensorflow-weights)

**Comment by rgeirhos** [comment]
Thanks for letting me know about your implementation. Apart from this, is there a repository-related question / issue?

**Comment by hcl14** [comment]
@rgeirhos No, just the interesting fact that colors are preserved when image is restored via backprop, for conv3_3 level.

**Comment by rgeirhos** [comment]
OK. I'm closing this issue then.

Concerning color preservation: isn't this to be expected? If you do the same approach with a vanilla VGG-16 model, shapes are preserved too while we know the model largely ignores object shape. In this sense, there clearly seems to be a difference between the features preserved through feature backpropagation and features actually used for classification.
