### ISSUE TITLE
Preprocessing images before feeding to ResNet

### ISSUE THREAD

**Issue by NagabhushanSN95** [rgeirhos/texture-vs-shape#15]
Do we need to preprocess the images before feeding them to Model A (ResNet trained on Stylized ImageNet)?

In `tensorflow.Keras`, there is a `preprocess_input()` function which subtracts ImageNet mean and does other preprocessing steps. Are any of those required for your model?

Also, should the images be fed in RGB format or BGR? 

I think it would be plenty helpful if you can include code to obtain features or predictions. That would answer many minor questions like this :)

**Comment by rgeirhos** [comment]
Input preprocessing is specified in the README. You can use the [PyTorch ImageNet training script](https://github.com/pytorch/examples/tree/master/imagenet) as a reference for obtaining predictions, which is exactly what I use.

I have added the input format (RGB not BGR) to the README (commit 303eab9).
