### ISSUE TITLE
ResNet model trained on edge maps of images in ImageNet

### ISSUE THREAD

**Issue by NagabhushanSN95** [rgeirhos/texture-vs-shape#16]
In the paper, you've tested the ResNet model (trained on IN and SIN) on edge maps of images in IN. Have you trained ResNet on edge maps of images in IN?

**Comment by rgeirhos** [comment]
Hey there. No, we never _trained_ models on edge maps, we only _tested_ models on edge images. The results of these tests can be found in Figure 2 (ImageNet-trained) and Figure 9 (Stylized-ImageNet-trained).
