### ISSUE TITLE
Fraction of 'shape' decisions and Fraction of 'texture' decisions

### ISSUE THREAD

**Issue by ruthvik92** [rgeirhos/texture-vs-shape#17]
Hi Robert,
Congrats on your good work. This is more of a question than an issue, in Figure 4: How did you decide "Fraction of 'shape' decisions" and "Fraction of 'texture' decisions". In case of humans you can simply ask them if they went with the shape or the texture but in the case of the CNNs how did you calculate the percentage of shape and texture bias?

**Comment by jadevaibhav** [comment]
I hope you are fine with me taking shot at this.

It is explained in the paper under 2.2 datasets, there is Original, Texture, cue conflict etc datasets used for pyscho-physical experiment. In cue conflict section, it is mentioned that the generated images use style from texture dataset. So, we have both original (shape) as well as texture (texture) label for this image. Hence,we have both labels.

Additionally, one more important thing to note is the author have mentioned that the participants were not informed of shape vs texture conflict, they voted for the class which felt most suitable for them.

Hope this answers your question.

**Comment by ruthvik92** [comment]
Thank you, I just wanted a confirmation on using two labels for the CNNs.
