### ISSUE TITLE
Would it be possible to share the pre-trained GoogleNet model? 

### ISSUE THREAD

**Issue by ProGamerGov** [rgeirhos/texture-vs-shape#20]
I'm interested in analyzing the neurons of the Stylized ImageNet GoogleNet model and seeing how they compare to a non stylized ImageNet dataset. I don't currently have access to the resources required to train a Stylized ImageNet GoogleNet model from scratch.

**Comment by rgeirhos** [comment]
Hi @ProGamerGov, I never trained a GoogLeNet on Stylized-ImageNet, so I'm afraid this won't be possible.
