### ISSUE TITLE
VGG-Trained-on-SIN Link not working

### ISSUE THREAD

**Issue by MKowal2** [rgeirhos/texture-vs-shape#21]
Not sure why, but the bitbucket link for the VGG16 network trained on SIN appears to be broken. Please let me know if this gets fixed!

https://bitbucket.org/robert_geirhos/texture-vs-shape-pretrained-models/raw/0008049cd10f74a944c6d5e90d4639927f8620ae/vgg16_train_60_epochs_lr0.01-6c6fcc9f.pth.tar

**Comment by rgeirhos** [comment]
I think https://github.com/rgeirhos/texture-vs-shape/blob/master/models/load_pretrained_models.py#L33 is what you're looking for.

**Comment by MKowal2** [comment]
Perfect. Thanks for the quick reply!
