### ISSUE TITLE
How to get a good combined image like this?

### ISSUE THREAD

**Issue by ymzlygw** [rgeirhos/texture-vs-shape#25]
Hi, thanks for your work firstly!
And I want to know how to combine 2 image and just change one's texture like following:
Original image (use texture):
![ori1](https://user-images.githubusercontent.com/17065855/113388462-3d3c3e80-93c9-11eb-908c-0664fc5757fb.jpeg)
combined image (use shape):
![co2](https://user-images.githubusercontent.com/17065855/113388505-4d541e00-93c9-11eb-9f25-18a5b9dd398f.png)

It look likes the cow‘s texture is placed on shark's shape. I don't think this is done by style transfer(or can be done by any AI tec?). And could you please tell me how to achieve it?

**Comment by rgeirhos** [comment]
Hi @ymzlygw, these images are super fun to look at!
You guessed it right, it's not done by style transfer so it isn't really related to this repo. I think you'll find more information [here](https://twitter.com/chriswolfvision/status/1333041228519268353?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1333041228519268353%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fbc3-production-assets-cdn.basecamp-static.com%2F3342189%2Fembeds%2FBAh7CEkiCGdpZAY6BkVUSSInZ2lkOi8vYmMzL0VtYmVkLzEzNTE3NDk_ZXhwaXJlc19pbgY7AFRJIgxwdXJwb3NlBjsAVEkiD2F0dGFjaGFibGUGOwBUSSIPZXhwaXJlc19hdAY7AFQw--769b6161dd3eca1becc44ac7a7313e4c5492b28f%2Fchat) and [there](https://chriswolfvision.medium.com/cow-sharks-exploring-the-shape-vs-texture-biases-in-deep-neural-networks-15d551910656).

Caveats when interpreting this in the context of texture vs. shape:

1.) apparently, the images are produced using digital morphing (stretching etc). It seems likely that this affects/distorts cow texture statistics.

2.) we don't know whether it's global shape that determines the fish prediction, or whether detecting local structures - such as the tip of a fin - is already sufficient

Hope this helps! ;)

**Comment by ymzlygw** [comment]
> Hi @ymzlygw, these images are super fun to look at!
> You guessed it right, it's not done by style transfer so it isn't really related to this repo. I think you'll find more information [here](https://twitter.com/chriswolfvision/status/1333041228519268353?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1333041228519268353%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fbc3-production-assets-cdn.basecamp-static.com%2F3342189%2Fembeds%2FBAh7CEkiCGdpZAY6BkVUSSInZ2lkOi8vYmMzL0VtYmVkLzEzNTE3NDk_ZXhwaXJlc19pbgY7AFRJIgxwdXJwb3NlBjsAVEkiD2F0dGFjaGFibGUGOwBUSSIPZXhwaXJlc19hdAY7AFQw--769b6161dd3eca1becc44ac7a7313e4c5492b28f%2Fchat) and [there](https://chriswolfvision.medium.com/cow-sharks-exploring-the-shape-vs-texture-biases-in-deep-neural-networks-15d551910656).
> 
> Caveats when interpreting this in the context of texture vs. shape:
> 
> 1.) apparently, the images are produced using digital morphing (stretching etc). It seems likely that this affects/distorts cow texture statistics.
> 
> 2.) we don't know whether it's global shape that determines the fish prediction, or whether detecting local structures - such as the tip of a fin - is already sufficient
> 
> Hope this helps! ;)

Thanks for your detailed replay!
