### ISSUE TITLE
pre-training weights

### ISSUE THREAD

**Issue by Seperendity** [rgeirhos/texture-vs-shape#27]
Are the pre-training weights for SIN publicly available?I would like to do some experiments based on this. Your articles have been a great inspiration to me. Thank you for your research！

**Comment by rgeirhos** [comment]
Do you mean those https://github.com/rgeirhos/texture-vs-shape#models?

**Comment by Seperendity** [comment]
Yes,i have found it. Thank you very much and good luck with your next amazing papers!

**Comment by rgeirhos** [comment]
Thanks ;)
