### ISSUE TITLE
Question about training details

### ISSUE THREAD

**Issue by Cheungki** [rgeirhos/texture-vs-shape#29]
Hi Robert, thanks for your nice work!

I have some questions about the training details. When training on SIN and IN, does the model just concat one batch from SIN and one batch from IN? BTW, should the batch from SIN correspond exactly to that from IN?

Thanks in advance.

**Comment by rgeirhos** [comment]
Thanks for your interest! For training on SIN+IN, I combined both datasets into one single large and trained on this large dataset in the usual way - i.e. sampling randomly, which means that a single batch usually contained some random IN and some random SIN images, without any additional constraints regarding identical images from IN and SIN in a single batch etc. - does this answer your question?

**Comment by Cheungki** [comment]
It really clears up my confusion. Thx again for your quick reply :)

**Comment by rgeirhos** [comment]
Glad to hear, and all the best for the model training!
