### ISSUE TITLE
Adversarial Examples 

### ISSUE THREAD

**Issue by boluoweifenda** [rgeirhos/texture-vs-shape#3]
Thanks for your thoughtful paper.
I am wondering whether the SIN model will be robust to adversarial attacks, e.g., FGSM. 
Since that adversarial noises added to IN models are more like meaningless textures, and SIN models are more focus on the shapes.
How do these adversarial examples derived from a white-box BP of the SIN model look like? 
I think it's worth a try : )

**Comment by rgeirhos** [comment]
Thanks for your interest, @boluoweifenda !
I haven't had the chance to take a systematic look at adversarial examples from our models, I'm afraid - so feel free to give it a go & let me know if you find anything interesting! ;)

**Comment by rgeirhos** [comment]
I just saw a paper on arXiv today that looked into some of these questions:
https://arxiv.org/pdf/1906.00335.pdf (Table 7)

**Comment by boluoweifenda** [comment]
thanks, that is much helpful !   @rgeirhos

**Comment by eminorhan** [comment]
We have also recently looked into this question in this pre-print: https://arxiv.org/pdf/1906.08416.pdf (Table 1 & Figure 3)

The upshot is that shape-based features don't seem to improve adversarial robustness against white-box attacks. They can, however, improve adversarial robustness under less stringent threat models.
