### ISSUE TITLE
Code for Texture-Shape Cue Conflict Analysis

### ISSUE THREAD

**Issue by DeepOceanDeep** [rgeirhos/texture-vs-shape#30]
Hi Robert 

Thanks for sharing materials in this repo. 

I'm curious about which code can assist me in feeding a CIFAR-10 or ImageNet dataset to any of the three CNNs you have mentioned in your paper, and obtaining a version that gives back the texture and shape cues conflicts images (just like the cat with elephant skin). Is it the code in the R section?  Also with the help of which code I can add noise to images just like the paper? And then train those three CNNs on the noisy images as well as SIN?

Thanks!
Flora

**Comment by rgeirhos** [comment]
Hi Flora,
Thanks for your interest. The repo provides images that can be used to test e.g. ImageNet-trained models, it doesn't provide CIFAR-10 data. If you'd like to add noise to images, you could e.g. use this here: https://github.com/rgeirhos/generalisation-humans-DNNs/blob/master/code/image_manipulation.py (different repo).

Here's more information on the code used to create cue conflict images: https://github.com/rgeirhos/texture-vs-shape#code-to-run-style-transfer

**Comment by DeepOceanDeep** [comment]
Thanks for your help Robert!

**Comment by rgeirhos** [comment]
My pleasure!
